# Ayso

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Ayso\:
        resource: './*'
        exclude:  './{AysoConnection.php}'

    App\Ayso\AysoConnection: '@doctrine.dbal.ayso_connection'

    # Just a test for manual tagging and old style service ids
    #rts.transformer:
    #    class: App\Ayso\RegionToSarTransformer
    #    public: true
    #    tags: { name: 'project.transformer'}
