security:

    encoders:
        App\User\User:
            id: App\User\UserEncoder

    providers:
        user_provider:
            id: App\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            switch_user:  true
            user_checker: App\User\UserChecker

            logout:
                path:   user_logout
                target: app_welcome

            form_login:
                provider:            user_provider

                login_path:          user_login
                check_path:          user_login_check
                default_target_path: app_home

                username_parameter:  username
                password_parameter:  password

                csrf_parameter:       _csrf_token
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager

    access_control:
        - { path: ^/home,       roles: ROLE_USER }
        - { path: ^/reg/person, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_USER:           []
        ROLE_STAFF:          [ROLE_USER]
        ROLE_REFEREE:        [ROLE_USER]

        ROLE_SCORE_ENTRY:    [ROLE_STAFF]
        ROLE_SCORE_ADMIN:    [ROLE_STAFF, ROLE_SCORE_ENTRY]

        ROLE_ASSIGNOR:       [ROLE_STAFF]

        ROLE_ASSIGNOR_ADMIN:
            - ROLE_ASSIGNOR

        ROLE_REFEREE_ADMIN:
            - ROLE_STAFF
            - ROLE_ASSIGNOR_ADMIN
            - ROLE_SCORE_ENTRY

        ROLE_ADMIN:
            - ROLE_STAFF
            - ROLE_ASSIGNOR_ADMIN
            - ROLE_SCORE_ADMIN
            - ROLE_REFEREE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            # ROLE_REFEREE
