security:

    encoders:
        App\User\User:
            id: App\User\UserEncoder

    providers:
        user_provider:
            id: App\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            switch_user: true

            logout:
                path:   user_logout
                target: app_welcome

            form_login:
                provider:            user_provider
                login_path:          user_login
                check_path:          user_login_check
                default_target_path: app_welcome

                username_parameter:  username
                password_parameter:  password

                csrf_parameter:       _csrf_token
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
