# Definitely needs some cleanup but export2 and import2 seems to be used
reg_team_listing:
    path: /listing
    defaults:
        _controller:    App\Reg\Team\Listing\RegTeamListingAction
        _view:          regteam_export_xls
        _role:          ROLE_ADMIN

regteam_export:
    path: /export
    defaults:
        _controller:    regteam_export_controller
        _view:          regteam_export_xls
        _role:          ROLE_ADMIN

reg_team_export2:
    path: /export2
    defaults:
        _controller:    reg_team_export_controller2
        _view:          reg_team_export_view_excel2
        _role:          ROLE_ADMIN

regteam_import:
    path: /import
    defaults:
        _controller:    regteam_import_controller
        _view:          regteam_import_view
        _role:          ROLE_ADMIN

reg_team_import2:
    path: /import2
    defaults:
        _controller:    reg_team_import_controller2
        _view:          reg_team_import_view2
        _role:          ROLE_ADMIN

regteam_transform:
    path: /transform
    defaults:
        _controller:    reg_team_transform_controller
        _view:          reg_team_transform_view
        _role:          ROLE_ADMIN
