# RegPerson

reg_person_update:
  path:       /update
  controller: App\RegPerson\Update\UpdateAction

reg_person_persons_update:
  path:       /persons/update
  controller: App\RegPerson\Persons\UpdateAction

reg_person_teams_update:
  path:       /teams/update
  controller: App\RegPerson\Teams\UpdateAction

