# User routes
user_login:
    path:       /login
    controller: App\Welcome\WelcomeAction

user_login_check:
    path:  /login-check

user_logout:
    path:  /logout

user_create:
    path: /create
    defaults:
        _controller: App\User\Create\UserCreateAction

user_update:
    path: /update
    defaults:
        _view:       user_update_view
        _controller: user_update_controller

# user password
user_password_update:
    path: /password/update
    defaults:
        _controller: user_password_update_action

user_password_reset_request:
    path: /password/reset-request
    defaults:
        _controller: App\User\Password\ResetRequest\PasswordResetRequestAction

user_password_reset_response:
    path: /password/reset-response/{token}
    defaults:
        token:       null
        _controller: App\User\Password\ResetResponse\PasswordResetResponseAction

# user social network
user_authen_connect:
    path:       /authen/connect/{providerName}
    controller: App\User\Authen\ConnectAction

user_authen_callback:
    path:       /authen/callback
    controller: App\User\Authen\CallbackAction
