services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false # Works thanks to ProjectLocator

    App\Project\:
        resource: './*'
        exclude:  './{ProjectContact.php,ProjectConnection.php}'

    App\Project\Project:
        factory: 'App\Project\ProjectFactory:create'
        arguments: ['%env(CURRENT_PROJECT)%']

    App\Project\ProjectConnection: '@doctrine.dbal.project_connection'
